config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  root 'welcome#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyGettingStarted</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_common_head.html.erb
<title><%= title_tag %></title>

<% if @camp.try(:persisted?) %>
  <meta name="og:title" content="<%= @camp.og_title %>" />
  <meta name="og:url" content="<%= camp_url(@project, protocol: 'https') %>" />
  <meta name="og:image" content="" />
  <meta name="og:description" content="Come join camp <%= @project.name %> on GoodNaps. <%= @camp.microwave %>"/>

<% else %>
  <meta name="og:title" content="GoodNap: Find a camp and get some naps" />
  <meta name="og:url" content="https://www.goodnaps.com/" />
  <!-- <meta name="og:image" content="" /> -->
  <meta name="og:description" content="Don't be left out while camping out. Create a camp, invite your friends, organize and party!"/>
<% end %>

<!-- <meta name="google-site-verification" content="bFbq4jNvHVioHo7FPq8iSY9HFFn3wY1_jM87o37OFKY" /> -->
<!-- <link rel="shortcut icon" href="#" /> -->

<%= stylesheet_link_tag "application" %>
<% if current_user %>
  <%= stylesheet_link_tag "user" %>
<% end %>  
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<%= javascript_include_tag "application" %>

<% if current_user %>
  <%= javascript_include_tag "user" %>
<% end %>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
    <div class="row">
      <div class="col-md-2">
        <div class="col-md-stack-space"></div> 
        <h4>GoodNaps</h4>
        <ul>
          <li><%= link_to 'Home', '/' %></li>
          <li><%= link_to 'Create a Camp', create_camp_path %></li>
          <li><%= link_to 'Join a Camp', join_camp_path %></li> 
        </ul>
      </div>
      <div class="col-md-2">
        <div class="col-md-stack-space"></div> 
        <h4>Get Social</h4>
        <ul>
          <li><%= link_to 'Twitter', 'http://twitter.com/goodnapsapp', target: :blank %><li>
          <li><%= link_to 'Facebook', 'http://facebook.com/goodnaps', target: :blank %><li>
        </ul>
      </div>
      
      <div class="col-md-2">
        <div class="col-md-stack-space"></div> 
        <h4>Company</h4>
        <ul>
          <li><%= link_to 'About', about_path %></li>
          <li><a class="help-box hlinks" data-toggle="modal" data-target="#help-box" href="#">Contact Us</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="row last-links">
      <div class="col-md-12">
        <div class="col-md-stack-space"></div> 
        <p>&copy; GoodNap <%= Time.now.year %> an Another Color Company
        <a href="http://www.entrepreneurialbynature.com/" target="_blank">
          <i class="ss-icon ss-gizmo ss-location"></i> Made in colorful Colorado
        </a>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_google.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54470414-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/welcome/index.erb
<!DOCTYPE html>
<html ng-app lang="en">
  <head>
    <%= render 'shared/common_head' %> 
    <%= yield :head %>
    <%= csrf_meta_tags %>
  </head>

  <body <%= body_spy.html_safe %> class="<%= body_class %> <%= extra_body_class %> <%= yield :body_class %> <%= body_state_classes %>">
    <%= content_for?(:content) ? yield(:content) : yield %>

    <div class="md-overlay"></div>
    <%= javascript_include_tag :codrop %>
    <%= render partial: 'shared/google' %>
  </body>
</html>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>